### ISSUE TITLE
[BUG] LEVEL 4 Immortality Bug

### ISSUE THREAD

**Issue by suhynnoh** [dev-jjjjjeong-bin/Invaders-SDP#73]
## Problem Description

In **LEVEL 4**, the player's health drops below 0, but the game does not trigger the "Game Over" screen as expected. This bug allows the player to continue playing despite having no remaining health, breaking the intended game mechanics. This issue has been confirmed **only in LEVEL 4**, while there were no problems in **LEVEL 1, 2, 3, and Boss levels**. However, **LEVEL 5, 6, 7** have not yet been tested for this issue.

## Todo List

-   [ ] Investigate the health check logic in LEVEL 4.
-   [ ] Confirm if the issue is present in LEVEL 5, 6, and 7.
-   [ ] Fix the issue where the game fails to transition to "Game Over" when health is 0 or below.
-   [ ] Test the fix in all levels to ensure the issue no longer occurs.

## Feature Description

https://github.com/user-attachments/assets/b536a245-d3ae-4bb9-b13c-831804324bd2

## Additional Information

The issue seems isolated to LEVEL 4 at the moment. However, further testing in LEVEL 5, 6, and 7 is necessary to determine if the bug exists in those levels as well.

**Comment by DongWonLee2** [comment]
There seems to be a problem with the actionPerformed message in the EnemyShipFormation file. When using the index of the list in the method, it is necessary to ensure that it does not deviate from the valid range (from 0 to the length of the list - 1).

**Comment by Dream-no24** [comment]
Could you explain how the list index issue in the `actionPerformed` method is related to the bug where the game doesn't end when the player's health reaches zero? I will make the modification for stability, but I don't fully understand the connection.

**Comment by Dream-no24** [comment]
Also, when I checked, I found that the same problem appeared in level 5 and 6.
<img width="682" alt="스크린샷 2024-10-16 오후 10 16 45" src="https://github.com/user-attachments/assets/dfa5b0ef-0d7f-4e0b-bd48-1983f727611c">

**Comment by DongWonLee2** [comment]
> Could you explain how the list index issue in the `actionPerformed` method is related to the bug where the game doesn't end when the player's health reaches zero? I will make the modification for stability, but I don't fully understand the connection.

I'm sorry, there was a mistake. I was talking about this after seeing a message from another bug.
